exec(open("train_NCA_normal_HP35.py").read())
exec(open("train_NCA_normal_LP35.py").read())
exit()
exec(open("train_NCA_highpass.py").read())
exec(open("train_NCA_lowpass.py").read())
exec(open("train_Unet_highpass.py").read())
exec(open("train_Unet_lowpass.py").read())